import { AnalysisReport } from '../types/detector.ts';

/**
 * Format the analysis report into a clean, human-readable Markdown string.
 */
export function formatReportMarkdown(report: AnalysisReport): string {
  const dateStr = new Date(report.timestamp).toLocaleString();

  let md = `# AI Writing Detector — Linguistic & Stylometric Report\n\n`;
  md += `**Timestamp:** ${dateStr}\n`;
  md += `**AI-Likelihood Score:** ${report.score}/100\n`;
  md += `**Classification:** ${report.classification}\n`;
  md += `**Raw Score (before cap):** ${report.rawScore}\n\n`;

  md += `> **Disclaimer:** ${report.disclaimer}\n\n`;

  md += `## 1. Text Statistics\n`;
  md += `- **Characters:** ${report.statistics.charCount}\n`;
  md += `- **Words:** ${report.statistics.wordCount}\n`;
  md += `- **Sentences:** ${report.statistics.sentenceCount}\n`;
  md += `- **Paragraphs:** ${report.statistics.paragraphCount}\n`;
  md += `- **Average Word Length:** ${report.statistics.avgWordLength} characters\n`;
  md += `- **Average Sentence Length:** ${report.statistics.avgSentenceLength} words\n\n`;

  md += `## 2. Category Score Contributions\n`;
  md += `| Category | Score | Cap | % of Final Score |\n`;
  md += `| :--- | :--- | :--- | :--- |\n`;
  for (const cat of report.categorySummaries) {
    md += `| ${cat.label} | ${cat.normalizedScore} | ${cat.maxCap} | ${cat.percentContribution}% |\n`;
  }
  md += `\n`;

  md += `## 3. Linguistic & Stylometric Factors\n`;
  for (const factor of report.linguisticFactors) {
    md += `### ${factor.name}\n`;
    md += `- **Measured Value:** ${factor.measuredValue}\n`;
    md += `- **Score Contribution:** +${factor.scoreContribution}\n`;
    md += `- **Interpretation:** ${factor.interpretation}\n`;
    md += `- **Details:** ${factor.explanation}\n\n`;
  }

  md += `## 4. Detected Patterns & Evidence\n`;
  for (const det of report.detectors) {
    if (det.detected && det.occurrences > 0) {
      md += `### ${det.name} (${det.category})\n`;
      md += `- **Occurrences:** ${det.occurrences}\n`;
      md += `- **Score Contribution:** +${det.cappedScore} (raw: ${det.rawScore}, cap: ${det.maxCap})\n`;
      md += `- **Explanation:** ${det.explanation}\n`;
      if (det.evidence.length > 0) {
        md += `- **Evidence Quotes:**\n`;
        for (const ev of det.evidence.slice(0, 5)) {
          md += `  - "${ev.matchedText}" — *${ev.explanation}*\n`;
        }
      }
      md += `\n`;
    }
  }

  md += `\n---\n*Generated by AI Writing Detector — Deterministic Heuristic Stylometry Tool*`;
  return md;
}

export function downloadJsonReport(report: AnalysisReport, filename = 'ai-writing-detector-report.json') {
  const jsonStr = JSON.stringify(report, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
